### ISSUE TITLE
Not working on 1.19

### ISSUE THREAD

**Issue by DatHardie** [ol-loginov/wot_tank_sets#1]
The Addon is currently not working for the last two updates.

**Comment by ol-loginov** [comment]
Ok, will look into it tonight

**Comment by ol-loginov** [comment]
I didn't notice any problems. If they are in the folder "mods/1.19.0.2":

* com.github.ol_loginov.wot_tank_sets_1.19.0.2.wotmod (or 1.18.1, no matter)
* izeberg.modsettingsapi_1.5.4.wotmod
* poliroid.modslistapi_1.4.1.wotmod

then everything works as it should.

Please describe what exactly you expect to see, but do not receive.

**Comment by ol-loginov** [comment]
Maybe it is conflicting with some other mod you have?

**Comment by DatHardie** [comment]
Okay I did some testing.
The new version from github is working standalone.
It is also working with https://wgmods.net/4322/
This is not the case wit the official version here https://wgmods.net/5516/
At least for me.

**Comment by ol-loginov** [comment]
Unfortunately, I cannot neither update the mod at wgmods.net nor update the description there, I'm in CIS regions, and Lesta Games has no such a mod portal here.
Github releases are the only option for now to get the actual version. And I don't know if it works with EU version of client

**Comment by DatHardie** [comment]
The current github Version is working on the EU Server.
