### ISSUE TITLE
XVM configuration for this mod?

### ISSUE THREAD

**Issue by KWJG** [ol-loginov/wot_tank_sets#2]
Could you please give us an instruction for XVM users? I want to use it in combination with XVM, and I'm willing to disable the XVM carousel features through config tweaking, but don't know how.

**Comment by ol-loginov** [comment]
I'm not familiar with XVM configs, but here is the way I did:

1) install latest XVM with XVM installer
2) in game folder "res_mods/configs/xvm/default" there is a file named "carousel.xc"
3) edit that file with any editor (notepad, for example) and set "enabled" there to "false" (see a screenshot)
4) now you may use this mod with tank filters. Unpack an "com.github.ol_loginov.wot_tank_sets_1.20.0.1.zip" to "mods/1.20.0.1" and launch the client.


 
![carousel xc](https://user-images.githubusercontent.com/1007300/229374476-74939875-b162-4f4b-bba7-a45c38b453a4.png)

**Comment by KWJG** [comment]
Many thanks!

I think adding this information to the mod introduction (both in the wgmods and github) will benefit a lot.

I'm sure that many people want to use this mod in combination with XVM, but won't try the mod because of XVM incompatibility. By giving them this instruction, I think more people will try the mod.
